### ISSUE TITLE
River Styx Boats', Harpies Trains', Neptune Ride's, and Hover Cars' Preview Image doesn't alter when changing Palette

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/objects#217]
Multiple Ride Type thumbnails use a predetermined palette, whereas other ride types in the game use the palette from the open park

![Github Park 2022-09-11 22-04-10](https://user-images.githubusercontent.com/94884086/189561552-fdd0ec8b-e4ff-402e-b8e8-71e2229d5dd3.png)

hovercars have been fixed.
Neptune Ride is fixed.
River Styx is fixed.
@ZeeMaji fixed the harpies trains.

**Comment by SpartanFrederic104** [comment]
This also affects the Harpies Trains for the Lay-down Roller Coaster and Hover Cars for the Car Ride.
![Wasteland of Dying Dreams 2022-09-11 19-12-06](https://user-images.githubusercontent.com/61885939/189561939-fe42f6a0-35ac-4502-95bd-9679c3929304.png)
![Gemini City 2558 2022-09-11 19-12-59](https://user-images.githubusercontent.com/61885939/189562001-98993848-08c7-4223-b38d-55d615d76722.png)

**Comment by ZeeMajora** [comment]
The issue also appears to be in the neptune ride thumbnail.
![Screenshot_select-area_20220913173351](https://user-images.githubusercontent.com/42477864/190013694-7cb950b7-e1fc-4568-ad85-ad0efc9f1571.png)

**Comment by SpartanFrederic104** [comment]
Oh right, I forgot about that one.

**Comment by SpartanFrederic104** [comment]
From what I can observe, the preview thumbnails for the River Styx Boats, Neptune Ride, Hover Cars, and Harpies Trains were digitally altered after they were cropped from their respective screenshots, which is why they don't change even after you change the water color in the park. The way to fix them is to reconstruct them in the same way as we did the RCT1 vehicle thumbnails, but with the water set to Natural Water and the preview thumbnails left untouched after cropping.

**Comment by 733737** [comment]
I think majora will make them once the rct1 vehicles are finished
